# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-11-05 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published', '-pk')},
        ),
    ]
